### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by Kisfeles** [Patrick2562/PYHABOT#11]
A bugfix után is out of range hibát kapok:
A legfrisebb verziót használom.
Nem tudom mi lehet a gond.

![issue](https://github.com/Patrick2562/PYHABOT/assets/99392134/de159b6b-fc96-4564-b03f-c128aa21571a)

**Comment by gptrk0** [comment]
A linket küldd el kérlek.

**Comment by Kisfeles** [comment]
https://hardverapro.hu/aprok/mobil/mobil/iphone/keres.php?stext=&stcid_text=&stcid=&stmid_text=&stmid=&minprice=&maxprice=85000&cmpid_text=&cmpid=&usrid_text=&usrid=&buying=0&stext_none=&noiced=1

**Comment by Kisfeles** [comment]
Több linkkel is próbáltam de nem működik, próbáltam kitörölni a hirdetésfigyelőket, újra meghívni a botot de nem megy sajna.

**Comment by gptrk0** [comment]
A databank mappát próbáltad törölni és úgy indítani a botot?

**Comment by Kisfeles** [comment]
Azt még nem. 1/1 töröljem ki?

**Comment by gptrk0** [comment]
Aha

**Comment by Kisfeles** [comment]
Kitöröltem, hozzáadtam újból a linket és ugyanaz a hiba

**Comment by gptrk0** [comment]
Töltsd le a legfrissebb verziót és azzal próbáld újra.

**Comment by Kisfeles** [comment]
Rendben, töltöm

**Comment by Kisfeles** [comment]
![error1](https://github.com/Patrick2562/PYHABOT/assets/99392134/118905be-8eb2-4dce-a217-267b35ecfc3c)
![error2](https://github.com/Patrick2562/PYHABOT/assets/99392134/6a19ef54-a765-47eb-adf7-9991931fac51)

**Comment by Kisfeles** [comment]
requirements installkor ezt a 2 hibát dobja egyébként

**Comment by Kisfeles** [comment]
nemtudom ez befolyásolhatja-e

**Comment by Kisfeles** [comment]
Most működik úgy tűnik, végre megy a rescrape is.
