### ISSUE TITLE
KeyError: 'TOKEN'

### ISSUE THREAD

**Issue by RRuben2006** [Patrick2562/PYHABOT#12]
PS D:\Ruben\Downloads\PYHABOT-master\PYHABOT-master> python run.py
Traceback (most recent call last):
  File "D:\Ruben\Downloads\PYHABOT-master\PYHABOT-master\run.py", line 23, in <module>
    main()
  File "D:\Ruben\Downloads\PYHABOT-master\PYHABOT-master\run.py", line 6, in main
    if config["TOKEN"] == "False":
       ~~~~~~^^^^^^^^^
KeyError: 'TOKEN'

**Comment by RRuben2006** [comment]
Szia! Kérhetek egy kis segítséget ezzel az erroral kapcsolatban? Köszi!

**Comment by gptrk0** [comment]
Szia, a Discord bot tokent beírtad a .env fájlba?

**Comment by RRuben2006** [comment]
Szia! Igen beírtam

**Comment by gptrk0** [comment]
és átnevezted a .env.example fájlt .env-re?
hogy írtad be (kép)?

**Comment by RRuben2006** [comment]
Igen átneveztem.
![kép_2024-09-22_130059986](https://github.com/user-attachments/assets/4d95d1bf-6808-4edf-ba33-8320bb5af0ec)

**Comment by gptrk0** [comment]
simán **.env** legyen a neve, copyexample nélkül

**Comment by RRuben2006** [comment]
Ez megoldotta, köszönöm a segítséget!
