### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by mobvadasz2** [Patrick2562/PYHABOT#6]
![unknown (4)](https://user-images.githubusercontent.com/61991767/183878390-7c278d5e-7dc4-48d5-91fe-0d7593f2aa2e.png)
Kb 1 nap után ilyen lesz magától, semmit nem csinálok vele, elfelejti az eddig keresett hirdetéseket.

**Comment by gptrk0** [comment]
Fixed by [b5e6389](https://github.com/Patrick2562/PYHABOT/commit/b5e6389672d668ffa1eb5496fddab98d9d09ec54)
